/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.zanyx.advent

import java.io.File

fun main() {
    val grid = TreeGridParser.parse(File("input.txt").inputStream())
    println(grid.flatten().count(Tree::isVisible))
}
