/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.zanyx.advent

import java.io.File

fun main() {
    val game = Game(rounds = GameRoundsParser.parse(File("input.txt").readLines()))
    println("Player score is ${game.resolve()}")
}
