/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.zanyx.advent

import java.io.File

fun main() {
    val findMessageStartMarker = FindMessageStartMarker()
    findMessageStartMarker(File("input.txt").inputStream())?.let {
        println(it)
    }
}
